name: Docker Container Run

on: [push]

jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: |
          echo "Сборка Docker образа..."
          docker build -t lab8-image .
          
      - name: Run container
        run: |
          echo "Запуск контейнера..."
          docker run --name lab8-container lab8-image
          echo "Логи контейнера:"
          docker logs lab8-container
          docker cp lab8-container:/app/output.log .
          
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: container-logs
          path: output.log
