name: Docker Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and run
        run: |
          docker build -t lab8-image .
          mkdir -p output
          docker run --rm -v ./output:/app lab8-image
          
      - name: Upload log
        uses: actions/upload-artifact@v3
        with:
          name: build-log
          path: output/build.log
