name: Docker Test

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t lab8-image .
        
      - name: Run container
        run: |
          mkdir -p output
          docker run --rm -v $(pwd)/output:/app/output lab8-image
          
      - name: Check logs
        run: |
          echo "=== Логи контейнера ==="
          cat output/output.log || echo "No logs found"
          
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: docker-logs
          path: output/
