name: Docker CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: |
          echo "=== Проверка Dockerfile ==="
          cat Dockerfile
          docker build -t lab8-image .
        
      - name: Run container
        run: |
          mkdir -p output
          docker run --rm -v $(pwd)/output:/app/output lab8-image
          echo "=== Логи контейнера ==="
          cat output/output.log || echo "Логи не найдены"
          
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs
          path: output/
